const words = [
    { word: "Abafar", meaning: "Impedir que algo seja ouvido, percebido ou divulgado.", example: "Eles tentaram abafar a discussão." },
    { word: "Abaixar", meaning: "Colocar algo em nível mais baixo; diminuir.", example: "Você pode abaixar o volume?" },
    { word: "Abalançar", meaning: "Movimentar de um lado para o outro; fazer oscilar.", example: "O vento fez a árvore abalançar." },
    { word: "Abalar", meaning: "Provocar forte impacto emocional ou estrutural.", example: "A notícia abalou toda a equipe." },
    { word: "Abalizar", meaning: "Delimitar ou orientar com referências.", example: "O projeto foi abalizado por normas técnicas." },
    { word: "Abalroar", meaning: "Colidir violentamente.", example: "O carro acabou abalroando o poste." },
    { word: "Abanar", meaning: "Produzir vento com movimento para refrescar.", example: "Ele abanou o rosto por causa do calor." },
    { word: "Abandonar", meaning: "Deixar algo ou alguém de forma definitiva.", example: "Ele decidiu abandonar o projeto." },
    { word: "Abastecer", meaning: "Fornecer o que é necessário; reabastecer.", example: "Vou abastecer o carro antes da viagem." },
    { word: "Abater", meaning: "Fazer cair; reduzir; ou eliminar.", example: "Os custos foram abatidos do orçamento." },
    { word: "Abduzir", meaning: "Retirar à força; sequestrar.", example: "A história fala de alguém que foi abduzido." },
    { word: "Abençoar", meaning: "Desejar o bem; consagrar.", example: "Ela pediu para o padre abençoar a casa." },
    { word: "Aberrar", meaning: "Desviar do que é normal ou esperado.", example: "Esse comportamento parece aberrante." },
    { word: "Abismar", meaning: "Causar espanto ou admiração profunda.", example: "O resultado me deixou abismado." },
    { word: "Abnegar", meaning: "Renunciar em favor de algo maior.", example: "Ele abnegou interesses pessoais pelo grupo." },
    { word: "Abominar", meaning: "Sentir repulsa extrema.", example: "Ela abomina qualquer tipo de injustiça." },
    { word: "Abordar", meaning: "Tratar de um assunto; aproximar-se.", example: "Vamos abordar esse tema na reunião." },
    { word: "Aborrecer", meaning: "Causar irritação; entediar.", example: "Não quero te aborrecer com isso." },
    { word: "Abrandar", meaning: "Tornar menos intenso.", example: "A chuva começou a abrandar." },
    { word: "Absorver", meaning: "Assimilar; incorporar.", example: "Ele conseguiu absorver bem o conteúdo." },
    { word: "Abster", meaning: "Deixar de fazer algo voluntariamente.", example: "Vou me abster de comentar." },
    { word: "Abusar", meaning: "Usar de forma excessiva ou indevida.", example: "Não abuse da paciência das pessoas." },
    { word: "Acabar", meaning: "Chegar ao fim.", example: "O prazo vai acabar hoje." },
    { word: "Acalentar", meaning: "Aconchegar; alimentar uma esperança.", example: "Ela ainda acalenta o sonho de viajar." },
    { word: "Aceitar", meaning: "Concordar; receber.", example: "Eu aceito sua proposta." },
    { word: "Acessar", meaning: "Entrar; obter acesso.", example: "Você consegue acessar o sistema?" },
    { word: "Acionar", meaning: "Colocar em funcionamento.", example: "Vou acionar o suporte técnico." },
    { word: "Aclarar", meaning: "Tornar claro; esclarecer.", example: "Preciso aclarar esse ponto." },
    { word: "Acompanhar", meaning: "Ir junto; observar o andamento.", example: "Eu acompanho o projeto desde o início." },
    { word: "Aconselhar", meaning: "Dar orientação.", example: "Eu te aconselho a revisar o contrato." },
    { word: "Acontecer", meaning: "Ter lugar; ocorrer.", example: "O problema aconteceu ontem." },
    { word: "Acoplar", meaning: "Unir ou conectar partes.", example: "Você pode acoplar esse módulo?" },
    { word: "Acordar", meaning: "Despertar; chegar a um acordo.", example: "Vamos acordar isso na reunião." },
    { word: "Acreditar", meaning: "Ter fé ou convicção.", example: "Eu acredito no seu potencial." },
    { word: "Acrescentar", meaning: "Adicionar algo.", example: "Vou acrescentar uma observação." },
    { word: "Adaptar", meaning: "Ajustar a uma nova situação.", example: "Precisamos adaptar o projeto." },
    { word: "Administrar", meaning: "Gerir; conduzir.", example: "Ela administra a empresa." },
    { word: "Admitir", meaning: "Reconhecer; permitir.", example: "Ele admitiu o erro." },
    { word: "Adotar", meaning: "Escolher; assumir.", example: "Vamos adotar uma nova estratégia." },
    { word: "Afirmar", meaning: "Declarar com certeza.", example: "Ele afirmou que vai participar." },
    { word: "Ajustar", meaning: "Regular; adequar.", example: "Vou ajustar os parâmetros." },
    { word: "Analisar", meaning: "Examinar detalhadamente.", example: "Precisamos analisar os dados." },
    { word: "Aplicar", meaning: "Utilizar na prática.", example: "Vamos aplicar esse método." },
    { word: "Aprimorar", meaning: "Melhorar.", example: "Queremos aprimorar o sistema." },
    { word: "Avaliar", meaning: "Julgar; estimar.", example: "O gestor vai avaliar o desempenho." },
    { word: "Averiguar", meaning: "Investigar; verificar.", example: "Vamos averiguar o ocorrido." },
    { word: "Colaborar", meaning: "Trabalhar em conjunto.", example: "Todos precisam colaborar." },
    { word: "Comunicar", meaning: "Transmitir informação.", example: "Vou comunicar a equipe." },
    { word: "Conectar", meaning: "Unir; estabelecer ligação.", example: "Conecte o cabo ao computador." },
    { word: "Decidir", meaning: "Escolher uma opção.", example: "Precisamos decidir hoje." },
    { word: "Desenvolver", meaning: "Criar; fazer evoluir.", example: "Eles vão desenvolver um novo produto." },
    { word: "Executar", meaning: "Colocar em prática.", example: "Vamos executar o plano." },
    { word: "Gerenciar", meaning: "Administrar recursos.", example: "Ela gerencia o projeto." },
    { word: "Implementar", meaning: "Introduzir oficialmente.", example: "Vamos implementar a nova função." },
    { word: "Melhorar", meaning: "Tornar melhor.", example: "Queremos melhorar o atendimento." },
    { word: "Organizar", meaning: "Estruturar; ordenar.", example: "Vou organizar os arquivos." },
    { word: "Planejar", meaning: "Definir etapas antecipadamente.", example: "Precisamos planejar o projeto." },
    { word: "Resolver", meaning: "Encontrar solução.", example: "Vamos resolver isso agora." },
    { word: "Testar", meaning: "Verificar funcionamento.", example: "Vamos testar o sistema." },
    { word: "Validar", meaning: "Confirmar como correto.", example: "É preciso validar os dados." }
];
